App/stockTrading/stockTrading/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/', accounts_views.UserRegisterView.as_view(), name='register'),
]

App/stockTrading/website/urls.py
from django.urls import path
from .views import home_view, line_chart, line_chart_json, deposit_view, trade_history, portfolio_view

urlpatterns = [
    path('', home_view, name='home'),
    path('deposit', deposit_view, name='deposit'),
    path('portfolio', portfolio_view, name='portfolio'),
    path('trades', trade_history, name='trades'),
    path('chart', line_chart, name='line_chart'),
    path('chartJSON', line_chart_json, name='line_chart_json'),
]

App/stockTrading/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE 
import datetime

# Create your models here.
class Wallet(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    balance = models.FloatField(default=0)

class Deposit(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    amount = models.FloatField(default=0)
    date = models.DateTimeField(default = datetime.datetime.now())

class Trade(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    stock = models.CharField(max_length=20)
    amount = models.FloatField(default=0)
    current_value = models.FloatField(default=0)
    quantity = models.FloatField()
    date = models.DateTimeField(default = datetime.datetime.now())
    last_updated = models.DateTimeField(default = datetime.datetime.now())
    type = models.CharField(max_length=4)
    is_open = models.BooleanField(default=True)
    open_price = models.FloatField()
    target = models.FloatField()
    trailing_sl = models.FloatField()
    close_price = models.FloatField(null=True)

class Stock(models.Model):
    stock = models.CharField(max_length=20)
    ltp = models.FloatField()
    last_updated = models.DateTimeField(default = datetime.datetime.now())

App/stockTrading/website/models.py
from django.db import models

# Create your models here.

App/stockTrading/website/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.urls import reverse
from chartjs.views.lines import BaseLineChartView
from Data import main_predict
from accounts.models import Deposit, Wallet, Trade, Stock
from django.db.models import Sum
import pandas as pd


class home(TemplateView):
    template_name='website/home.html'
    def get(self, request):
        symbol_list = pd.read_csv("App/stockTrading/Data/ind_nifty50list.csv")
        symbol_list = symbol_list["Symbol"].tolist()
        context = {}
        context['stock'] = request.GET.get('stock')
        context['stock_list'] = symbol_list
        if(request.user.is_authenticated):
            context['deposits'] = Deposit.objects.filter(user = request.user).aggregate(Sum('amount'))['amount__sum']
            wallet = Wallet.objects.filter(user = request.user)
            if wallet.count():
                context['balance'] = wallet.first()
            else:
                context['balance'] = {'balance': None}
            context['open_trades'] = Trade.objects.filter(user = request.user).count()
            context['traded_amount'] = Trade.objects.filter(user = request.user).aggregate(Sum('amount'))['amount__sum']
            if context['stock'] is not None:
                return redirect('{}?stock={}'.format(reverse('line_chart'), request.GET.get('stock')))
            else:
                return render(request, 'website/home.html', context)
        else:
            return redirect(reverse('login'))

class trades(TemplateView):
    template_name='website/tables.html'

    def get(self, request):
        symbol_list = pd.read_csv("App/stockTrading/Data/ind_nifty50list.csv")
        symbol_list = symbol_list["Symbol"].tolist()
        context = {}
        context['stock'] = request.GET.get('stock')
        context['stock_list'] = symbol_list
        if(request.user.is_authenticated):
            context['trades'] = Trade.objects.filter(user = request.user)
            return render(request, self.template_name, context)
        else:
            return redirect(reverse('login'))

class portfolio(TemplateView):
    template_name='website/portfolio.html'

    def get(self, request):
        symbol_list = pd.read_csv("App/stockTrading/Data/ind_nifty50list.csv")
        symbol_list = symbol_list["Symbol"].tolist()
        context = {}
        context['stock'] = request.GET.get('stock')
        context['stock_list'] = symbol_list
        if(request.user.is_authenticated):
            trades = Trade.objects.filter(user = request.user).filter(is_open = True)
            investment = 0
            current_value = 0
            buy_trades = trades.filter(type = 'buy')
            sell_trades = trades.filter(type = 'sell')
            if buy_trades.count():
                investment = investment + float(buy_trades.aggregate(Sum('amount'))['amount__sum'])
            if sell_trades.count():
                current_value = current_value + float(sell_trades.aggregate(Sum('amount'))['amount__sum'])
            for trade in sell_trades:
                symbol = trade.stock
                cmp = float(Stock.objects.filter(stock = symbol).first().ltp)
                investment += cmp*float(trade.quantity)
                trade.current_value = cmp*float(trade.quantity)
                trade.save()
            for trade in buy_trades:
                symbol = trade.stock
                cmp = float(Stock.objects.filter(stock = symbol).first().ltp)
                current_value += cmp*float(trade.quantity)
                trade.current_value = cmp*float(trade.quantity)
                trade.save()
            context['investment'] = investment
            context['current_value'] = current_value
            context['trades'] = trades
            context['pl'] = current_value - investment
            return render(request, self.template_name, context)
        else:
            return redirect(reverse('login'))
            
class LineChartJSONView(BaseLineChartView):

    df_list = []

    def get_labels(self):
        """Return 7 labels for the x-axis."""
        df_list = main_predict.predict_data(self.request.GET.get('stock'))
        index_list = []
        for i in range(len(df_list[1])):
            index_list.append("Day - " + str(i+1))
        x = index_list
        self.df_list = df_list
        return x

    def get_providers(self):
        """Return names of datasets."""
        return ["CLOSE", "SVR", "LSTM"]

    def get_data(self):
        """Return 3 datasets to plot."""

        y0 = self.df_list[0]['Close'].tolist()
        y1 = self.df_list[1].tolist()
        y1_proxy = []
        for i in range(len(y1)):
            y1_proxy.append(y1[i][0])
        y2 = self.df_list[2].tolist()
        y2_proxy = []
        for i in range(len(y2)):
            y2_proxy.append(y2[i][0])
        return [y0, y1_proxy, y2_proxy]


class lc(TemplateView):
    template_name='website/charts.html'

    symbol_list = pd.read_csv("App/stockTrading/Data/ind_nifty50list.csv")
    symbol_list = symbol_list["Symbol"].tolist()

    def get(self, request):
        context = {}
        context['stock'] = request.GET.get('stock')
        context['stock_list'] = self.symbol_list
        if(request.user.is_authenticated):
            return render(request, self.template_name, context)
        else:
            return redirect(reverse('login'))

class deposit(TemplateView):
    template_name='website/deposit.html'

    symbol_list = pd.read_csv("App/stockTrading/Data/ind_nifty50list.csv")
    symbol_list = symbol_list["Symbol"].tolist()

    def get(self, request):
        context = {}
        context['stock'] = request.GET.get('stock')
        context['stock_list'] = self.symbol_list
        if(request.user.is_authenticated):
            context['deposits'] = Deposit.objects.filter(user_id = request.user.id)
            return render(request, self.template_name, context)
        else:
            return redirect(reverse('login'))
    
    def post(self, request):
        context = {}
        context['stock'] = request.GET.get('stock')
        context['stock_list'] = self.symbol_list
        if(request.user.is_authenticated):
            context['deposits'] = Deposit.objects.filter(user_id = request.user.id)
            amount = request.POST.get('amount')
            new_deposit = Deposit(amount = amount, user = request.user)
            new_deposit.save()
            wallet = Wallet.objects.filter(user=request.user)
            if wallet.first() is None:
                wallet = Wallet(balance = float(amount), user = request.user)
            else:
                wallet = wallet.first()
                wallet.balance = wallet.balance + float(amount)
            wallet.save()
            return render(request, self.template_name, context)
        else:
            return redirect(reverse('login'))

line_chart = lc.as_view()
line_chart_json = LineChartJSONView.as_view()
home_view = home.as_view()
deposit_view = deposit.as_view()
trade_history = trades.as_view()
portfolio_view = portfolio.as_view()

App/stockTrading/website/templates/website/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Stock Trading with AI</title>

    <!-- Custom fonts for this template-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="{% static 'website/vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'website/css/sb-admin-2.css'%}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{%url 'home'%}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            {% if request.user.is_authenticated %}
            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="{%url 'home'%}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link" href="{%url 'portfolio'%}">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Portfolio</span>
                </a>
            </li>

            <!-- Nav Item - Deposits -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'deposit' %}">
                    <i class="fas fa-fw fa-coins"></i>
                    <span>Deposits</span></a>
            </li>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'line_chart' %}">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Charts</span></a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'trades' %}">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Trades</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            {% endif %}

            <!-- Sidebar Toggler (Sidebar)
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div> -->

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    {% if request.user.is_authenticated %}
                    <!-- Topbar Search -->
                    <form method="GET"
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <select name="stock" type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                                {% for stocks in stock_list %}
                                <option value={{stocks}} {% if stocks == stock %} selected={{stock}} {% endif %}>{{stocks}}</option>
                                {% endfor %}
                            </select>
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user}}</span>
                                <img class="img-profile rounded-circle"
                                    src="{% static 'img/undraw_profile.svg' %}">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{%url 'logout'%}" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                        {% endif %}

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    {% if messages%}
                    {% for message in messages%}
                    <div class="alert alert-{{message.tags}}">
                        {{message}}
                    </div>
                    {% endfor %}
                    {% endif %}
                  {% block content %}{% endblock %}
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{%url 'logout'%}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'website/vendor/jquery/jquery.min.js'%}"></script>
    <script src="{% static 'website/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'website/vendor/jquery-easing/jquery.easing.min.js'%}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'website/js/sb-admin-2.min.js'%}"></script>

    <script src="{% static 'website/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'website/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>

</body>

</html>

App/stockTrading/website/templates/website/charts.html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
{% extends "website/base.html" %}
{% load static %}
{% block content %}
        {% if stock is not None %}
        <h1>Chart for {{stock}}</h1>
        <div class="chart-container">

  <div class="preloader-wrapper big active" style="height: 250px; width: 250px; margin-top: 10%;">
    <div class="spinner-layer spinner-blue-only">
      <div class="circle-clipper left">
        <div class="circle"></div>
      </div><div class="gap-patch">
        <div class="circle"></div>
      </div><div class="circle-clipper right">
        <div class="circle"></div>
      </div>
    </div>
  </div>
  <h3 class="wait-message" style="margin-top: 4%">Please wait while the model loads...</h3>
        <canvas id="myAreaChart" width="1300" height="838" style="animation: chartjs-render-animation 1ms;"></canvas>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.3.2/chart.min.js" integrity="sha512-VCHVc5miKoln972iJPvkQrUYYq7XpxXzvqNfiul1H4aZDwGBGC0lq373KNleaB2LpnC2a/iNfE5zoRYmB4TRDQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-zoom/1.0.0/chartjs-plugin-zoom.min.js" integrity="sha512-IhRtzxlPU7PMu47R132Y5BYVZCCuHNcds+Q3Wg2iL11J+fda93ugoQwy+LR2d68l2AudqQsAGhgXbGxSzKS9gA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js" integrity="sha512-UXumZrZNiOwnTcZSHLOfcTs0aos2MzBWHXOHOuB0J/R44QB0dwY5JgfbvljXcklVf65Gc4El6RjZ+lnwd2az2g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script type="text/javascript">
            $.get('{% url "line_chart_json" %}?stock={{stock}}', function(data) {
                var ctx = $("#myAreaChart").get(0).getContext("2d");
                for(i=0;i < data['datasets'].length; i++)
                {
                data['datasets'][i].lineTension = 0;
                data['datasets'][i].pointRadius = 1;
                data['datasets'][i].backgroundColor = 'transparent';
                }

                data['datasets'][0].borderColor = '#665191';
                data['datasets'][1].borderColor = '#ff6361';
                data['datasets'][2].borderColor = '#ffa600';
                
                window.myAreaChart = new Chart(ctx, 
                {
                    type: 'line', 
                    data: data,    
                    options: {
                        responsive: true,
                        tooltips: { 
                            backgroundColor: "rgb(255,255,255)",
                            bodyFontColor: "#858796",
                            titleMarginBottom: 10,
                            titleFontColor: '#6e707e',
                            titleFontSize: 14,
                            borderColor: '#dddfeb',
                            borderWidth: 1,
                            xPadding: 15,
                            yPadding: 15,
                            displayColors: false,
                            intersect: false,
                            mode: 'index',
                            caretPadding: 10,
                            callbacks: {
                                label: function(tooltipItem, chart) {
                                var datasetLabel = chart.datasets[tooltipItem.datasetIndex].label || '';
                                return datasetLabel + ': INR ' + tooltipItem.yLabel;
                                }
                            }
                        },
                        scales: {
                            xAxes: [{
                                time: {
                                    unit: 'date'
                                },
                                gridLines: {
                                    display: false
                                },
                                ticks: {
                                    maxTicksLimit: 7
                                }
                            }],
                            yAxes:[{
                                gridLines: {
                                    display: false
                                }
                            }]
                        },
                        plugins: {
                            zoom: {
                                zoom: {
                                    drag: {
                                        enabled: true
                                    },
                                    mode: 'xy',
                                }
                            }
                        }
                    }
                });
                $('.preloader-wrapper').hide();
                $('.wait-message').hide();
            });
        </script>
        <button onclick="resetZoom()">Reset Zoom</button>
        <script>
            function resetZoom() {
                window.myAreaChart.resetZoom();
            }
        </script>
        {% else %}
        {% endif %}
{% endblock %}

App/stockTrading/website/templates/website/deposit.html
{% extends 'website/base.html' %}
{% load static %}
{% block content %}
<!-- Page Heading -->
<style>
    
#outer-wrapper {
	display: flex;
	flex-direction: column;
	padding: 20px;
}

#input-price {
    width: 100%;
	padding: 40px;
	border-radius: 10px;
	text-align: center;
	box-shadow: rgba(0, 0, 0, 0.19) 0px 10px 20px, rgba(0, 0, 0, 0.23) 0px 6px 6px;

}

#input-price h2 {
	margin-bottom: 30px;
}

.amount {
	font-size: 1.5rem;
}

input[type="submit"] {
	border: none;
	outline: none;
	border-radius: 10px;
	padding: 10px;
	font-size: 1.25rem;
	background-color: green;
	color: white;
	cursor: pointer;
}

#table-div {
	padding: 40px;
	margin-top: 40px;
}

#table-div h2 {
	text-align: center;
	margin-bottom: 30px;
}

#table-div table {
	width: 100%;
	text-align: center;
}

.scrolldown {
	border-collapse: collapse;
	overflow-y: scroll;
	display: inline-block;
	color: #d4f1f4;
	background-color: #05445e;
	border-radius: 10px;
	width: 100%;
}

.scrolldown thead th {
	position: sticky;
	top: 0;
}

th,
td {
	padding: 10px 20px;
	text-align: center;
	width: 500px;
}

th {
	background: #189ab4;
	line-height: 1.75rem;
}

tr:nth-child(2n) {
	background-color: #075577;
}

::-webkit-scrollbar {
	width: 0px;
}

::-webkit-scrollbar-track {
	background-color: transparent;
}

::-webkit-scrollbar-thumb {
	background-color: #d6dee1;
	border-radius: 20px;
	border: 6px solid transparent;
	background-clip: content-box;
}

::-webkit-scrollbar-thumb:hover {
	background-color: #a8bbbf;
}

</style>
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{user.first_name}}Deposit</h1>
</div>
<div id="outer-wrapper">
    <!-- Content Row -->
    <div class="row">
        <div id="input-price">
            
            <form action="" method="post">
                {% csrf_token %}
                <h2>Deposit Amount</h2>
                <label for="price" class="amount">Amount: </label>
                <input type="number" name="amount" id="id_amount" required step="0.5" min="1"/>
                <br><br>
                <center><input type="submit" name="Submit" value="Submit" /></center>
            </form>
        </div>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div id="table-div">
            <h2>Desposit History</h2>
            <table class="scrolldown">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Date</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for deposit in deposits %}
                    <tr>
                        <td>{{deposit.id}}</td>
                        <td>{{deposit.date}}</td>
                        <td>{{deposit.amount}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Content Row -->
<div class="row">

    <!-- Content Column -->
    <div class="col-lg-6 mb-4">
    </div>
</div>
<script src="{% static 'website/vendor/jquery/jquery.min.js'%}"></script>
<script src="{% static 'website/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'website/vendor/jquery-easing/jquery.easing.min.js'%}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'website/js/sb-admin-2.min.js'%}"></script>

<!-- Page level plugins -->
<script src="{% static 'website/vendor/chart.js/Chart.min.js'%}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'website/js/demo/chart-area-demo.js'%}"></script>
<script src="{% static 'website/js/demo/chart-pie-demo.js'%}"></script>
{% endblock %}

App/stockTrading/website/templates/website/tables.html
{% extends 'website/base.html' %}
{% load static %}
{% block content %}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Recent Trades</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Trade ID</th>
                        <th>Symbol</th>
                        <th>Amount (INR)</th>
                        <th>Quantity Traded</th>
                        <th>Date</th>
                        <th>Action</th>
                        <th>Open</th>
                        <th>Trade Open Price</th>
                        <th>Target Price</th>
                        <th>Trailing Stop Loss</th>
                        <th>Trade Close Price</th>
                    </tr>
                </thead>
                <tbody>
                    {% for trade in trades %}
                    <tr>
                        <td>{{trade.id}}</td>
                        <td>{{trade.stock}}</td>
                        <td>{{trade.amount}}</td>
                        <td>{{trade.quantity}}</td>
                        <td>{{trade.date}}</td>
                        <td>{{trade.type}}</td>
                        <td>{{trade.is_open}}</td>
                        <td>{{trade.open_price}}</td>
                        <td>{{trade.target}}</td>
                        <td>{{trade.trailing_sl}}</td>
                        <td>{{trade.close_price}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}